### ISSUE TITLE
Unable to go to the statistics (/shorturl+) page with the newly created URL . 

### ISSUE THREAD

**Issue by ertuncb** [christian-krieg/yourls-plugin-base-url-rewrite#1] opened 2024-03-05 22:34 UTC
The original URL is seamlessly replaced with the new URL (url.mydomain.com/xyz -> go.mydomain.com/xyz)
However, since the link to the statistics on the admin page has also changed and there is a + character at the end of this URL (go.mydomain.com/xyz+), the statistics page cannot be accessed. The probable reason is that the + sign at the end of the STATS page turns into a space character during URL Rewrite.

The content of the .htaccess file is as follows:
```
<IfModule mod_rewrite.c>
RewriteEngine On

#redirect "go.mydomain.com/shorturl" to the original "url.mydomain.com/shorturl" URL
RewriteCond %{HTTP_HOST} ^go\.mydomain\.com [NC]
RewriteRule (.+) https://url.mydomain.com/$1 [R=302,L]

</IfModule>
```

**Comment by christian-krieg** [comment] 2024-03-06 12:25
I suspect the root cause may be with redirects back to ``url.mydomain.com``; have you tested your URL rewrites in your ``.htaccess``? Do they work as expected?

**Comment by ertuncb** [comment] 2024-03-07 12:07
If you mean the shortened, newly created go.mydomain.com/shorturl addresses, then yes, these work fine. 
It seems like the problem is caused by the + character in go.mydomain.com/xyz+. In the short research I did, I read that the + sign is always replaced with a space during redirection.
If the problem is caused by this, the only solution I can think of is not to change the URL links of the stats, share, etc. buttons to go.mydomain, but to leave them in their original form (url.mydomain).
![image](https://github.com/christian-krieg/yourls-plugin-base-url-rewrite/assets/56238655/a0bda429-f76e-45b5-979e-c1f82374ac6a)

**Comment by christian-krieg** [comment] 2024-03-07 12:14
I mean if the webserver that hosts ``go.mydomain.com`` properly redirects requests back to ``url.mydomain.com``. I guess this is what you intend to do with your ``.htaccess``. Can you confirm that this works?

**Comment by ertuncb** [comment] 2024-03-07 15:59
Yes. 
I use the admin interface at https://url.mydomain.com/admin. Shortened URLs are generated here as go.mydomain.com/short.  When I enter go.mydomain.com/short in the web browser, it is redirected to url.mydomain.com/short with redirect. And it works.

**Comment by christian-krieg** [comment] 2024-03-08 14:04
@ertuncb, Thank you very much for clarifying this! As this *BaseURL Rewrite* plugin only changes the behavior of **generating** the short links, I don't really have an idea how it may affect the accessibility of the *stats* pages. I tested the behavior on my setups, and I do not have any problems accessing the statistics pages.

The only logical conclusion I may come up with is to triple-check the URL rewrite in your ``.htaccess``. Probably it works if you escape the ``+`` sign? What happens if you use ``https://go.mydomain.com/short%2B`` instead of ``https://go.mydomain.com/short+``?

**Comment by ertuncb** [comment] 2024-03-10 15:58
Unfortunately, writing /short%2B did not work either. 

But I've finally found a solution. The problem was solved when I added **N**o **E**scape to 
RewriteRule (.+) https://url.mydomain.com/$1 **[R=302,L]**

New version:
RewriteRule (.+) https://url.mydomain.com/$1 **[R=302,NE,L]**
(thank you for your quick response)

**Comment by christian-krieg** [comment] 2024-03-11 05:15
That's great, thx for the update! I guess we are good to close the issue?

**Closed as completed by christian-krieg** 2024-03-11 05:15 UTC
